### ISSUE TITLE
WebSocket provider and autoreconnect improvements

### ISSUE THREAD

**Issue by tiagoalves** [tinode/tinode-js#19]
I'm having some minor issues with the `autoreconnect` and the `setWebSocketProvider()` features.

Regarding `autoreconnect`, it is not possible to disable or in any way configure the reconnection strategy. For instance, the maximum delay between reconnects is up to 34 minutes which seems very inadequate for a real-time chat platform. This is of course debatable but I was looking at something like 30 - 60s.

To work around this, I tried to use [reconnecting-websocket](https://github.com/pladaria/reconnecting-websocket) which allows me to fine tune reconnection settings. The problem is now that when the WebSocket connection is lost, an `onclose()` event is triggered and tinde-js discards the reference it has to the WebSocket provider with `_socket = null`, [here](https://github.com/tinode/tinode-js/blob/master/src/tinode.js#L698).

When the __same__ socket successfully reconnects a few moments later, an `onopen()` event is triggered and tinode-js tries to send the `"hi"` packet but has no reference to `_socket` and thus throws "Websocket is not connected".

I've forked tinode-js and simply removed all `_socket = null` statements and that seems to fix the situation. (I've not done extensive testing to make sure that my changes don't break other situations)

a) What do you think about having a way to configure the `autoreconnect` feature in the Tinode constructor params?
b) Are you open to changes to better support third-party WebSocket providers?

**Comment by or-else** [comment]
> For instance, the maximum delay between reconnects is up to 34 minutes which seems very inadequate for a real-time chat platform.

That's debatable :)

The reconnect strategy is a randmized exponential backoff which is essentially an industry standard. 34 minutes delay happens only if the previous 10 attempts to connect to the server have failed.

**a)** I suppose what's really missing is "reconnect now". When the app moves to a foreground or some other event happens it needs to get the connection immediately. It should be able to interrupt the exponential backoff timer. 

I can expose exponential backoff settings too, but I think it would be suboptimal. It's very hard to find a balance between not DoS-ing your own server and keeping connections snappy.

> When the same socket successfully reconnects a few moments later

That's unexpected. Maybe it's the WS provider you use but it's not supposed to happen with the browser's WS implementation. The purpose of `_socket = null` is to indicate that the socket is no longer useable because it failed to connect. What you are saying is that the socket is usable after a failed connection attempt. I'll double check. If I'm wrong let's just remove the `_socket = null`.

**b)** I'm fine with supporting other WS providers. I just don't want to support incompatible providers, i.e. I don't want code like `if (wsprovider == foo) { abc } else if (wsprovider == bar) { def } else ...`

**Comment by or-else** [comment]
The latest release has the _Reconnect Now_ UI https://github.com/tinode/chat/releases/tag/v0.15.11-rc2

<img width="341" alt="screenshot 2018-12-17 at 15 56 17" src="https://user-images.githubusercontent.com/5938143/50088669-b6252580-0214-11e9-9524-a6cf4c003a47.png">
